### ISSUE TITLE
WRITE_SECURE_SETTINGS problem

### ISSUE THREAD

**Issue by pistachit1** [eternalodball/hikepy#1]
After some troubleshooting, I'm having the following error and I'm really tired of it. (by the way we have the same phone)

Any suggestions 

Error:
Message: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command ''C:\\Program Files\\Android\\platform-tools\\adb.exe' -P 5037 -s 44d377dd shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy'' exited with code 255'; Command output: Security exception: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS

java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS
        at com.android.providers.settings.SettingsProvider.enforceWritePermission(SettingsProvider.java:2050)
        at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1256)
        at com.android.providers.settings.SettingsProvider.deleteGlobalSetting(SettingsProvider.java:1239)
        at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:476)
        at android.content.ContentProvider.call(ContentProvider.java:2177)
        at android.content.ContentProvider$Transport.call(ContentProvider.java:477)
        at com.android.providers.settings.SettingsService$MyShellCommand.deleteForUser(SettingsService.java:399)
        at com.android.providers.settings.SettingsService$MyShellCommand.onCommand(SettingsService.java:281)
        at android.os.ShellCommand.exec(ShellCommand.java:111)
        at com.android.providers.settings.SettingsService.onShellCommand(SettingsService.java:49)
        at android.os.Binder.shellCommand(Binder.java:881)
        at android.os.Binder.onTransact(Binder.java:765)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
Security exception: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS

java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS
        at com.android.providers.settings.SettingsProvider.enforceWritePermission(SettingsProvider.java:2050)
        at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1256)
        at com.android.providers.settings.SettingsProvider.deleteGlobalSetting(SettingsProvider.java:1239)
        at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:476)
        at android.content.ContentProvider.call(ContentProvider.java:2177)
        at android.content.ContentProvider$Transport.call(ContentProvider.java:477)
        at com.android.providers.settings.SettingsService$MyShellCommand.deleteForUser(SettingsService.java:399)
        at com.android.providers.settings.SettingsService$MyShellCommand.onCommand(SettingsService.java:281)
        at android.os.ShellCommand.exec(ShellCommand.java:111)
        at com.android.providers.settings.SettingsService.onShellCommand(SettingsService.java:49)
        at android.os.Binder.shellCommand(Binder.java:881)
        at android.os.Binder.onTransact(Binder.java:765)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
Security exception: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS

java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS
        at com.android.providers.settings.SettingsProvider.enforceWritePermission(SettingsProvider.java:2050)
        at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1256)
        at com.android.providers.settings.SettingsProvider.deleteGlobalSetting(SettingsProvider.java:1239)
        at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:476)
        at android.content.ContentProvider.call(ContentProvider.java:2177)
        at android.content.ContentProvider$Transport.call(ContentProvider.java:477)
        at com.android.providers.settings.SettingsService$MyShellCommand.deleteForUser(SettingsService.java:399)
        at com.android.providers.settings.SettingsService$MyShellCommand.onCommand(SettingsService.java:281)
        at android.os.ShellCommand.exec(ShellCommand.java:111)
        at com.android.providers.settings.SettingsService.onShellCommand(SettingsService.java:49)
        at android.os.Binder.shellCommand(Binder.java:881)
        at android.os.Binder.onTransact(Binder.java:765)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)

Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command ''C:\\Program Files\\Android\\platform-tools\\adb.exe' -P 5037 -s 44d377dd shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy'' exited with code 255'; Command output: Security exception: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS

java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS
        at com.android.providers.settings.SettingsProvider.enforceWritePermission(SettingsProvider.java:2050)
        at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1256)
        at com.android.providers.settings.SettingsProvider.deleteGlobalSetting(SettingsProvider.java:1239)
        at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:476)
        at android.content.ContentProvider.call(ContentProvider.java:2177)
        at android.content.ContentProvider$Transport.call(ContentProvider.java:477)
        at com.android.providers.settings.SettingsService$MyShellCommand.deleteForUser(SettingsService.java:399)
        at com.android.providers.settings.SettingsService$MyShellCommand.onCommand(SettingsService.java:281)
        at android.os.ShellCommand.exec(ShellCommand.java:111)
        at com.android.providers.settings.SettingsService.onShellCommand(SettingsService.java:49)
        at android.os.Binder.shellCommand(Binder.java:881)
        at android.os.Binder.onTransact(Binder.java:765)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
Security exception: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS

java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS
        at com.android.providers.settings.SettingsProvider.enforceWritePermission(SettingsProvider.java:2050)
        at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1256)
        at com.android.providers.settings.SettingsProvider.deleteGlobalSetting(SettingsProvider.java:1239)
        at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:476)
        at android.content.ContentProvider.call(ContentProvider.java:2177)
        at android.content.ContentProvider$Transport.call(ContentProvider.java:477)
        at com.android.providers.settings.SettingsService$MyShellCommand.deleteForUser(SettingsService.java:399)
        at com.android.providers.settings.SettingsService$MyShellCommand.onCommand(SettingsService.java:281)
        at android.os.ShellCommand.exec(ShellCommand.java:111)
        at com.android.providers.settings.SettingsService.onShellCommand(SettingsService.java:49)
        at android.os.Binder.shellCommand(Binder.java:881)
        at android.os.Binder.onTransact(Binder.java:765)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
Security exception: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS

java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS
        at com.android.providers.settings.SettingsProvider.enforceWritePermission(SettingsProvider.java:2050)
        at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1256)
        at com.android.providers.settings.SettingsProvider.deleteGlobalSetting(SettingsProvider.java:1239)
        at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:476)
        at android.content.ContentProvider.call(ContentProvider.java:2177)
        at android.content.ContentProvider$Transport.call(ContentProvider.java:477)
        at com.android.providers.settings.SettingsService$MyShellCommand.deleteForUser(SettingsService.java:399)
        at com.android.providers.settings.SettingsService$MyShellCommand.onCommand(SettingsService.java:281)
        at android.os.ShellCommand.exec(ShellCommand.java:111)
        at com.android.providers.settings.SettingsService.onShellCommand(SettingsService.java:49)
        at android.os.Binder.shellCommand(Binder.java:881)
        at android.os.Binder.onTransact(Binder.java:765)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)

    at getResponseForW3CError (C:\Users\mimov\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\mimov\AppData\Local\Programs\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:380:37)

**Comment by pistachit1** [comment]
https://stackoverflow.com/questions/13045283/write-secure-settings-permission-error-even-when-added-in-manifest

If you could make it more intuitive thank you

**Comment by pistachit1** [comment]
https://stackoverflow.com/questions/52079343/how-can-i-use-adb-to-grant-permission-without-root 
this works for me but another error has existed (i close powershell but it said something like the user dont allow install something, i didn't touch nothing)

**Comment by eternalodball** [comment]
> https://stackoverflow.com/questions/52079343/how-can-i-use-adb-to-grant-permission-without-root this works for me but another error has existed (i close powershell but it said something like the user dont allow install something, i didn't touch nothing)

allow it in your developer mode settings in poco x3 it should be named as "**allow installing with adb**" or something like that ...

**Comment by pistachit1** [comment]
Thank you, I finally got everything working.
The problem now is that the fake account I was using to follow now doesn't work and I have to create another one . This is one problem after another. But at least the problem is getting easier to solve :)

**Comment by pistachit1** [comment]
Now I have a fake account but the automation does not work :(. I mean it doesn't follow anyone, it just keeps changing

**Comment by pistachit1** [comment]
#change-swipescroll-value)make compatible for your device (edit main.py)
Search for x1 , x2 , x3 & x4 (same goes for y1 - y4) and change value
change swipe/scroll value
see line 232 and change x , y value

Can you explain what values I have to put?

**Comment by pistachit1** [comment]
How can I make automation faster?

**Comment by eternalodball** [comment]
> How can I make automation faster?

check line 58 on main.py

**Comment by pistachit1** [comment]
> > ¿Cómo puedo hacer que la automatización sea más rápida?
> 
> verifique la línea 58 en main.py

Okey thanks, I think I'll put it faster.
For my part I tried to make a copy of the file and then try to remove the ppl-task 4 and make it refresh the page instead of scrolling down by removing the tasks where the ppl-task 4 appeared. Still there is something that still doesn't work, i.e. it works once or twice and then stops working. Like sometimes it doesn't change the tab to hiketop even though the screen coordinates are set correctly. It's as if sometimes I do the hiketop screen taps on instagram and then it stops working.

Translated with www.DeepL.com/Translator (free version)

**Comment by pistachit1** [comment]
maybe def follow_ig() is not working? Because of the first task yes i can follow but the others just no.

**Comment by pistachit1** [comment]
the def de seguir is definitely not working

**Comment by pistachit1** [comment]
I think I corrected it.
I have no idea about programming but I just noticed that it was written twice "try" in a strange place and some strange indentations.

Finally the def was like this for me


def follow_ig() :

    global NO_SUCH_ELEMENT
    try:

        NO_SUCH_ELEMENT = "False"
            
        FOLLOW_XPATH = '//android.widget.Button[@text="Follow"]'
            
        MESSAGE_XPATH = '//android.widget.Button[@text="Message"]'

        FOLLOWING_XPATH = '//android.widget.Button[@text="Following"]'

        try:

            CHECK_PRIVATE_STATUS = driver.find_element(By.XPATH, MESSAGE_XPATH).text

        except Exception as err:

            CHECK_PRIVATE_STATUS = "Private account"

        try:

            CHECK_FOLLOWING_STATUS = driver.find_element(By.XPATH, FOLLOWING_XPATH).text
            
        except Exception as err:

            CHECK_FOLLOWING_STATUS = "Not followed"

            
        if CHECK_FOLLOWING_STATUS == "Following":

            print("[+] NOT OK , FOLLOWED ACC ...")
            pass


        elif CHECK_PRIVATE_STATUS == "Private account":

            print("[+] NOT OK , PRIVATE ACC ...")
            pass

        else:

            driver.find_element(By.XPATH, FOLLOW_XPATH).click()
            print("[+] OK")

    except Exception as err:

        print("mistake not defined") # Doing mistake consciously

    except Exception as err:
    
        NO_SUCH_ELEMENT = "true"

**Comment by eternalodball** [comment]
> I think I corrected it. I have no idea about programming but I just noticed that it was written twice "try" in a strange place and some strange indentations.
> 
> Finally the def was like this for me
> 
> def follow_ig() :
> 
> ```
> global NO_SUCH_ELEMENT
> try:
> 
>     NO_SUCH_ELEMENT = "False"
>         
>     FOLLOW_XPATH = '//android.widget.Button[@text="Follow"]'
>         
>     MESSAGE_XPATH = '//android.widget.Button[@text="Message"]'
> 
>     FOLLOWING_XPATH = '//android.widget.Button[@text="Following"]'
> 
>     try:
> 
>         CHECK_PRIVATE_STATUS = driver.find_element(By.XPATH, MESSAGE_XPATH).text
> 
>     except Exception as err:
> 
>         CHECK_PRIVATE_STATUS = "Private account"
> 
>     try:
> 
>         CHECK_FOLLOWING_STATUS = driver.find_element(By.XPATH, FOLLOWING_XPATH).text
>         
>     except Exception as err:
> 
>         CHECK_FOLLOWING_STATUS = "Not followed"
> 
>         
>     if CHECK_FOLLOWING_STATUS == "Following":
> 
>         print("[+] NOT OK , FOLLOWED ACC ...")
>         pass
> 
> 
>     elif CHECK_PRIVATE_STATUS == "Private account":
> 
>         print("[+] NOT OK , PRIVATE ACC ...")
>         pass
> 
>     else:
> 
>         driver.find_element(By.XPATH, FOLLOW_XPATH).click()
>         print("[+] OK")
> 
> except Exception as err:
> 
>     print("mistake not defined") # Doing mistake consciously
> 
> except Exception as err:
> 
>     NO_SUCH_ELEMENT = "true"
> ```

Feel free to correct the code if it's wrong . It was working but I've done some changes in past to make it readable probably messed up there 😅
